## advance operation with business examples


In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# data structure: [restaurant_id,2021,2022,2023,2024]
sales_data=np.array([
    [1,150000,180000,220000,250000] ,#paradise
    [2,120000,140000,160000,190000],#beijing
    [3,200000,230000,260000,300000],# pizza hub
    [4,180000,210000,240000,270000], #burger point
    [5,160000,185000,205000,230000] #chai point
])

print("sale datashape: ",sales_data.shape) # to know the shape of the data
print("====Zomato sales analysis====")
print("sales data for the 1st 3 restaurants : ")
print(sales_data[np.arange(3),:])

print()

print(sales_data[0:3]) # sales_data[:3]
print()
print(sales_data[:,:3])
print()
print(sales_data[:,1:]) # this print only sales not the restaurant id

# to find the total sales of each restaurant

for i in range(5):
    sum_is=np.sum(sales_data[i,1:])
    print(f"the sum of the {i+1} id restaurant :",sum_is)



sale datashape:  (5, 5)
====Zomato sales analysis====
sales data for the 1st 3 restaurants : 
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

[[     1 150000 180000]
 [     2 120000 140000]
 [     3 200000 230000]
 [     4 180000 210000]
 [     5 160000 185000]]

[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
the sum of the 1 id restaurant : 800000
the sum of the 2 id restaurant : 610000
the sum of the 3 id restaurant : 990000
the sum of the 4 id restaurant : 900000
the sum of the 5 id restaurant : 780000
