## Numpy array and basics
learn about numpy from basics with chai aur code

In [2]:
import numpy as np

In [ ]:
arr_1d=np.array([1,2,3,5]) ## jab bhi hum array mai element daalenge toh vo list ke type mai daalenge
print(arr_1d)

[1 2 3 5]


In [5]:
arr_2d =np.array([
    [1,2,3,4,5],
    [0,4,2,9,3]
])

print(arr_2d)


[[1 2 3 4 5]
 [0 4 2 9 3]]


In [10]:
## multiplyling array v/s list
py_list=[1,2,3]

print("the multiplication of the list ",py_list*2)

py_arr1 =np.array([1,2,3])
print("the multiplication of the arr ",py_arr1*2)

py_arr2 =np.array([[1,2,3],[4,5,6]])
print("the multiplication of the arr ",py_arr2*2)


the multiplication of the list  [1, 2, 3, 1, 2, 3]
the multiplication of the arr  [2 4 6]
the multiplication of the arr  [[ 2  4  6]
 [ 8 10 12]]


In [6]:
# Now checking which is faster 
#1 list multiplication in py or numpy arr multiplication
import time as t
start=t.time()
list1_py=[i*2 for i in range(100)]
print(list1_py)
print("time taken to perform operations: ",t.time()-start)


start1=t.time()
arr=np.arange(100)*2
print(arr)
print("time taken to perform operations: ",t.time()-start1)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
time taken to perform operations:  0.00012373924255371094
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
time taken to perform operations:  0.0002582073211669922


In [24]:
zeroMatrix=np.zeros((4,3))  # (R,C)
print(zeroMatrix)
print("\n")

onesMatrix=np.ones((3,4))
print(onesMatrix)

print("\n")

fullMatrix=np.full((4,2),6)
print(fullMatrix)

print("\n")

randomMatrix=np.random.random((5,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[6 6]
 [6 6]
 [6 6]
 [6 6]]


[[0.2898919  0.79861945 0.79518862]
 [0.56297789 0.14385501 0.91627528]
 [0.30859974 0.71091939 0.29252422]
 [0.67069254 0.98504325 0.91551725]
 [0.27694052 0.85929553 0.28092974]]


In [28]:
# sequence
seq=np.arange(0,21,3)  # np.arange(start,stop,step) 
print(seq)

[ 0  3  6  9 12 15 18]


## vector Matrrix and Tensor

In [30]:
vector=np.array([1,2,3,5])

matrix=np.array([[1,2,3,4],[9,8,7,6]])

tensor=np.array([[[1,2,3,4],[5,6,7,8]],
                 [[9,10,11,12],[13,14,15,16]]])
print(vector)
print()
print(matrix)
print()
print(tensor)


[1 2 3 5]

[[1 2 3 4]
 [9 8 7 6]]

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


### Properties of the arrays

In [32]:
#shape and dimension and size
matrix=np.array([[1,2,3,4],[4,3,6,7],[0,8,9,1]])
print("shape ",matrix.shape)
print("dimension ",matrix.ndim)
print("size ",matrix.size)

print("data type ",matrix.dtype)

shape  (3, 4)
dimension  2
size  12
data type  int64


### Reshape the arrays

In [ ]:
arr=np.arange(12)
print("originl array ",arr)

reshaped_ar=arr.reshape((4,3))
print("\n reshapeed array ",reshaped_ar)

print()
flat_arr=reshaped_ar.flatten() # make a copy of the array in 1d 
print("flatten array ",flat_arr)

print()
raveled_ar=reshaped_ar.ravel() # dont make any copy 
print("ravel array ",raveled_ar)
print()

raveled_ar[5]=89 # i have make changes in the raveled but it also changes the original one 
print(reshaped_ar)




originl array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshapeed array  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

flatten array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

ravel array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2]
 [ 3  4 89]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# transpose of the matrix
# matrix.transpose     or  matrix.T

matrix=np.array([[4,9,2],
                 [3,8,1],
                 [5,6,0]])
trans_mat=matrix.transpose()
print(trans_mat) 

print()

mat2=np.array([[4,9,2],
                 [3,8,1],
                 [5,6,0]])

mat3=mat2 + matrix
print(mat3)
print()
tran_mat3=mat3.T
print(tran_mat3)

# if you want to make sum of all the elements of the arr
print()
sum_of_all= np.sum([matrix])
print(sum_of_all)



[[4 3 5]
 [9 8 6]
 [2 1 0]]

[[ 8 18  4]
 [ 6 16  2]
 [10 12  0]]

[[ 8  6 10]
 [18 16 12]
 [ 4  2  0]]

38
