In [50]:
import numpy as np

### Slicing and axes in the numpy arrays

In [ ]:
#slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3:10])
print(arr[3:-2])
print(arr[4])

arr2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr2d[1,2])
print(arr2d[1,-2])

print(arr2d[1,:]) # print entire row
print()
print(arr2d[1])  # print entire row
print()
print(arr2d[:,2]) # print entire column


[ 4  6  8 10]
[4 5 6 7 8]
5
7
7
[5 6 7 8]

[5 6 7 8]

[ 3  7 11]


### sorting in the numpy arrays

In [21]:
arr1d=np.array([1,6,3,8,3,9,6,4,0,7,2])
print(np.sort(arr1d))

arr_2d_unsorted=np.array([[3,10],[8,2],[9,7]])
print(" this sort the column wise: ",np.sort(arr_2d_unsorted,axis=0))
print()
print(" this sort the row wise: ",np.sort(arr_2d_unsorted,axis=1))



[0 1 2 3 3 4 6 6 7 8 9]
 this sort the column wise:  [[ 3  2]
 [ 8  7]
 [ 9 10]]

 this sort the row wise:  [[ 3 10]
 [ 2  8]
 [ 7  9]]


## Filter

In [3]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_nums=numbers[numbers%2==0] # numbers mai se vo number jo even ho 
print(even_nums)
print(numbers)

# here same for the odd numbers 
odd_nums=numbers[numbers%2!=0]
print(odd_nums)


[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


## Filter with mask


In [9]:
print(numbers)
mask=numbers>5
print("numbers greater than 5 ",numbers[mask])

[ 1  2  3  4  5  6  7  8  9 10]
numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing and np.where()

In [22]:
nums=np.array([1,5,3,2,6,7,8,9])
indices=[0,3,5]
print(nums[indices])

where_result=np.where(nums >= 5) # this stores the location / index of conditon 
print(where_result)
print("Np where : ",nums[where_result])



[1 2 7]
(array([1, 4, 5, 6, 7]),)
Np where :  [5 6 7 8 9]


In [35]:
# we can insert multiple conditions in the where clause 
condition_arr=np.where(nums>5,nums*4,nums)
print(condition_arr)

#it is acutually like this
# if(nums>5){
#     nums*4
#     }
# else{
#     nums
#     }
print(nums)
con1=np.where(nums%2==0,True,False)
print("tells which are even:\n",con1)

[ 1  5  3  2 24 28 32 36]
[1 5 3 2 6 7 8 9]
tells which are even:
 [False False False  True  True False  True False]


## adding and removing the data

In [49]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


## array compatibility


In [52]:
ar1=np.array([1,4,7,9])
ar2=np.array([9,6,3,1])

print("compatibility shapes ",ar1.shape==ar2.shape)

compatibility shapes  True


In [60]:
#adding the new row in the array
original_arr=([[1,2,3],[4,5,6]])
new_row =([8,7,9])
arr_with_newrow=np.vstack((original_arr,new_row))
print(arr_with_newrow)
print()
print(original_arr)
print()
new_col=([[4,3],[0,1]])
arr_with_newcol=np.hstack((original_arr,new_col))
print(arr_with_newcol)

[[1 2 3]
 [4 5 6]
 [8 7 9]]

[[1, 2, 3], [4, 5, 6]]

[[1 2 3 4 3]
 [4 5 6 0 1]]
