In [1]:
import numpy as np

### Slicing and axes in the numpy arrays

In [ ]:
#slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3:10])
print(arr[3:-2])
print(arr[4])

arr2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr2d[1,2])
print(arr2d[1,-2])

print(arr2d[1,:]) # print entire row
print()
print(arr2d[1])  # print entire row
print()
print(arr2d[:,2]) # print entire column


[ 4  6  8 10]
[4 5 6 7 8]
5
7
7
[5 6 7 8]

[5 6 7 8]

[ 3  7 11]


### sorting in the numpy arrays

In [21]:
arr1d=np.array([1,6,3,8,3,9,6,4,0,7,2])
print(np.sort(arr1d))

arr_2d_unsorted=np.array([[3,10],[8,2],[9,7]])
print(" this sort the column wise: ",np.sort(arr_2d_unsorted,axis=0))
print()
print(" this sort the row wise: ",np.sort(arr_2d_unsorted,axis=1))



[0 1 2 3 3 4 6 6 7 8 9]
 this sort the column wise:  [[ 3  2]
 [ 8  7]
 [ 9 10]]

 this sort the row wise:  [[ 3 10]
 [ 2  8]
 [ 7  9]]
